version: '3.3'

services:
    mysql:
        platform: linux/x86_64
        image: mysql:5
        environment:
            - MYSQL_DATABASE=del_rio
            - MYSQL_USER=root
            - MYSQL_ROOT_PASSWORD=admin123
            - MYSQL_PORT=3306
        ports:
            - 3308:3306
        volumes:
          - ./mysql_data:/var/lib/mysql
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
            - MYSQL_ROOT_PASSWORD=admin123
            - PMA_HOST=mysql
        ports:
            - 8080:80